export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_ALL_POSTS = 'RECEIVE_ALL_POSTS';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT='UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';